---
- name: learning about vars and var recall
  hosts: planetexpress

  vars:
          listofips:
                  - 192.168.1.1
                  - 10.15.1.3
                  - 172.16.5.7
          dlurl: "https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf"
  tasks: 
          - name: just print to the screen the value of listofips
            debug:
                    var: listofips

          - name: show second way to print to screen the value of listofips
            debug:
                    msg: "i want this message to appear on the screen {{ listofips }}"

          - name: download a critical pdf
            get_url:
                    url: "{{ dlurl }}"
                    dest: ~/ 
