---
- name: our first play book to install some software
  hosts: labhosts
  gather_facts: yes
  
  tasks:
          - name: module to install software with apt
            apt:
                    name: figlet
                    state: absent
            become: yes
